// File generated by FlutterFire CLI.
// Contains configuration for Firebase for your Flutter app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Mobile/desktop options
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK5fnMO1Ie3ziUv9s_YTKOLV6HmBz9bt0',
    appId: '1:712509417680:web:YOUR_WEB_APP_ID',
    messagingSenderId: '712509417680',
    projectId: 'handybuddy-518c6',
    authDomain: 'handybuddy-518c6.firebaseapp.com',
    storageBucket: 'handybuddy-518c6.firebasestorage.app',
    measurementId: 'YOUR_MEASUREMENT_ID', // This isn't in your JSON file
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK5fnMO1Ie3ziUv9s_YTKOLV6HmBz9bt0',
    appId: '1:712509417680:android:6ebde7dd0113b3d84596d5',
    messagingSenderId: '712509417680',
    projectId: 'handybuddy-518c6',
    storageBucket: 'handybuddy-518c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK5fnMO1Ie3ziUv9s_YTKOLV6HmBz9bt0',
    appId: '1:712509417680:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '712509417680',
    projectId: 'handybuddy-518c6',
    storageBucket: 'handybuddy-518c6.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID', // Not in your JSON file
    iosBundleId: 'com.example.handybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK5fnMO1Ie3ziUv9s_YTKOLV6HmBz9bt0',
    appId: '1:712509417680:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '712509417680',
    projectId: 'handybuddy-518c6',
    storageBucket: 'handybuddy-518c6.firebasestorage.app',
    iosClientId: 'YOUR_MACOS_CLIENT_ID', // Not in your JSON file
    iosBundleId: 'com.example.handybuddy',
  );
}